Hyperobjekt/seda-map

- src/components/base/Header.js
- src/components/map-view/Map.js
- src/components/map-view/MapControls.js
- src/components/map-view/MapLegend.js
- src/components/map-view/MapScatterplot.js
- src/components/map-view/MapSearch.js
- src/index.css
- src/index.js
- src/views/index.js
- src/views/map/index.js
> add layout CSS for map prototype

- src/components/base/Header.js
- src/views/index.js
> set header color, add logo

- .eslintrc
- src/components/base/Select.js
- src/components/map-view/Map.js
- src/components/map-view/MapControls.js
- src/constants/dataOptions.js
- src/index.css
- src/modules/map.js
- src/style/map-style.js
- src/withRoot.js
> Choropleth controls component

- src/components/map-view/Map.js
- src/components/map-view/MapLegend.js
- src/constants/dataOptions.js
- src/index.css
- src/modules/map.js
- src/style/map-style.js
> Map legend component

- src/components/map-view/Map.js
- src/constants/dataOptions.js
- src/index.css
- src/modules/map.js
- src/style/map-style.js
- src/style/style.json
progress on #9, loads in new data, shows schools
> update choropleths with new tileset data

- src/components/map-view/Map.js
- src/constants/dataOptions.js
- src/index.css
- src/style/map-style.js
- src/style/style.json
> Tooltips and hover states

- .travis.yml
- package-lock.json
- package.json
- src/actions/scatterplotActions.js
- src/components/map-view/Map.js
- src/components/map-view/MapLegend.js
- src/components/map-view/MapScatterplot.js
- src/modules/index.js
- src/modules/metrics.js
- src/modules/scatterplot.js
- src/modules/search.js
- src/style/map-style.js
Pulls scatterplot data loading into the redux state and dispatches actions for request / success / fail.  Updated deploy URL so it doesn't overwrite the map prototype
> Refactor redux state

- package-lock.json
- package.json
- src/components/map-view/Map.js
- src/components/map-view/MapScatterplot.js
- src/components/map-view/MapSearch.js
- src/index.css
will close #4, still need to update region based on what is selected
> search box

- src/components/base/Hint.js
- src/components/map-view/MapScatterplot.js
- src/constants/scatterOptions.js
- src/index.css
- src/modules/metrics.js
- src/views/map/index.js
closes #39 and uses hint component on scatterplot header
> scatterplot heading

- package-lock.json
- package.json
- src/components/map-view/Map.js
- src/components/map-view/MapControls.js
- src/components/map-view/MapLegend.js
- src/components/map-view/MapScatterplot.js
- src/components/map-view/MapTooltip.js
- src/modules/map.js
- src/modules/router.js
- src/views/index.js
> switch map state to route params

- package-lock.json
- package.json
- public/index.html
- src/actions/featuresActions.js
- src/actions/mapActions.js
- src/actions/searchActions.js
- src/components/map-view/Map.js
- src/components/map-view/MapLocation.js
- src/components/map-view/MapScatterplot.js
- src/components/map-view/MapSearch.js
- src/components/map-view/MapSelectedLocations.js
- src/components/map-view/MapTooltip.js
- src/index.css
- src/modules/features.js
- src/modules/index.js
- src/modules/router.js
- src/modules/selected.js
- src/style/map-style.js
- src/utils/index.js
- src/utils/tilequery.js
- src/views/index.js
- src/views/map/index.js
> Feature selection

- src/components/map-view/ColorStops.js
- src/components/map-view/Map.js
- src/components/map-view/MapControls.js
- src/components/map-view/MapLegend.js
- src/components/map-view/MapScatterplot.js
- src/index.css
- src/views/map/index.js
brings UI into single panel, drops below map on mobile.  Closes #35
> Responsive layout

- src/actions/featuresActions.js
- src/actions/mapActions.js
- src/components/map-view/Map.js
- src/components/map-view/MapLocation.js
- src/components/map-view/MapSelectedLocations.js
- src/components/map-view/ReportCard.js
- src/components/map-view/ReportCardSummary.js
- src/index.css
- src/modules/index.js
- src/modules/reportCard.js
- src/views/map/index.js
> Report card component

- src/components/map-view/MapLocation.js
- src/components/map-view/MapSelectedLocations.js
- src/components/map-view/MapTooltip.js
- src/constants/statesFips.js
- src/modules/features.js
- Adds states to tooltips and selected locations
> Add state names

- src/components/base/Controls.js
- src/components/map-view/MapScatterplot.js
- src/components/report-card/DynamicScatterplot.js
- src/components/report-card/LocationStats.js
- src/components/report-card/LocationStatsList.js
- src/components/report-card/ReportCard.js
- src/components/report-card/ReportCardSection.js
- src/constants/dataOptions.js
- src/index.css
- src/modules/report.js
- src/style/echartTheme.js
- src/style/scatterplot-style.js
> Opportunity Differences

- package-lock.json
- package.json
- src/components/map-view/MapSearch.js
- src/constants/lang.js
- src/index.css
- src/utils/index.js
- src/views/map/index.js
Replaces current search with `react-seda-search` component.  Allows searching multiple indices.
> add multi index search component

- src/actions/mapActions.js
- src/actions/scatterplotActions.js
- src/components/base/DynamicScatterplot.js
- src/components/map/Map.js
- src/components/map/MapScatterplot.js
- src/components/sections/AchievementGapSection.js
- src/components/sections/MapSection.js
- src/components/sections/OpportunityDifferencesSection.js
- src/components/sections/ScatterplotSection.js
- src/components/sections/SocioeconomicConditionsSection.js
- src/constants/statesFips.js
- src/css/sections/_index.css
- src/css/sections/scatterplot.css
- src/modules/config.js
- src/modules/report.js
- src/style/scatterplot-style.js
add control bar to each visual component, closes #72
> Visual component control bar

- src/components/base/LocationCards.js
- src/components/base/Search.js
- src/components/map/MapSearch.js
- src/components/sections/IntroSection.js
- src/components/sections/MapSection.js
- src/components/sections/ScatterplotSection.js
- src/constants/lang.js
- src/css/atoms/_index.css
- src/css/atoms/helper.css
- src/css/components/location-card-list.css
- src/css/components/location-card.css
- src/css/sections/_index.css
- src/views/map/index.js
> add card that allows adding another location

- src/components/map/Map.js
- src/components/sections/MapSection.js
- src/components/seda-map/SedaMap.js
- src/constants/dataOptions.js
- src/css/sections/intro.css
- src/modules/map.js
- src/modules/router.js
- src/style/map-style.js
- Split map component into presentational / smart components. 
- Increase outline visibility on highlighted and selected items (progress on #80)
> Refactor map component

- src/modules/router.js
- src/modules/selected.js
> Fix duplicate selections

- package-lock.json
- package.json
- src/components/base/CircleOverlay.js
- src/components/base/DynamicScatterplot.js
- src/components/base/LocationCards.js
- src/components/base/Section.js
- src/constants/dataOptions.js
- src/constants/lang.js
- src/css/components/_index.css
- src/css/components/circle-overlay.css
- src/css/components/location-card-list.css
- src/css/components/location-card.css
- src/modules/config.js
- src/modules/scatterplot.js
- src/style/scatterplot-style.js
- src/utils/index.js
- card stacking
- card transitions
- use separate layer for rendering selected dots (closes #104)
- change base layer to use "large" flag when there is a state highlighted (faster rendering)
- use lang file for metric language
> Scatterplot Performance

- src/actions/mapActions.js
- src/actions/sectionActions.js
- src/components/base/DynamicScatterplot.js
- src/components/sections/AchievementGapSection.js
- src/components/sections/MapSection.js
- src/components/sections/OpportunityDifferencesSection.js
- src/components/sections/SocioeconomicConditionsSection.js
- src/constants/statesFips.js
- src/css/components/circle-overlay.css
- src/css/sections/_index.css
- src/modules/map.js
- src/modules/router.js
- src/style/scatterplot-style.js
- src/views/index.js
- src/views/map/index.js
Route is now `/:highlightedState/:region/:metric/:demographic/:zoom/:lat/:lon/:locations`, closes #103
> Track highlighted state in route

- package-lock.json
- package.json
- src/components/base/DynamicScatterplot.js
- src/components/base/Map.js
- src/components/sections/AchievementGapSection.js
- src/components/sections/MapSection.js
- src/components/sections/OpportunityDifferencesSection.js
- src/components/sections/SocioeconomicConditionsSection.js
- src/css/components/_index.css
- src/css/components/blocker.css
- src/css/components/location-card-list.css
- src/css/components/location-card.css
- src/css/global.css
- src/css/pages/_index.css
- src/css/pages/map-tool.css
- src/css/sections/_index.css
- src/css/sections/intro.css
- src/css/sections/scatterplot.css
- src/modules/sections.js
- src/utils/index.js
- src/views/map/index.js
> conditional rendering

- src/components/base/CircleOverlay.js
- src/components/base/DynamicScatterplot.js
- src/components/base/LocationCard.js
- src/modules/scatterplot.js
> check for zero value in location cards

- src/components/base/DynamicScatterplot.js
- src/components/sections/AchievementGapSection.js
- src/components/sections/MapSection.js
- src/components/sections/OpportunityDifferencesSection.js
- src/components/sections/SocioeconomicConditionsSection.js
> use circle overlay to show hovered location

- src/components/sections/IntroSection.js
- src/css/components/card.css
- src/css/pages/map-tool.css
- src/css/sections/intro.css
- src/css/sections/map.css
> Responsive intro

- src/components/base/DynamicScatterplot.js
- src/css/components/blocker.css
- src/css/components/card.css
- src/css/components/location-card-list.css
- src/css/sections/_index.css
> horizontal scroll cards on small resolutions

- package-lock.json
- package.json
> update search component to match states and cities

- src/components/base/DynamicScatterplot.js
- src/views/map/index.js
> clear dot on hover out of scatterplot

- src/components/base/Map.js
> resize map on window resize

- src/css/components/location-card-list.css
- src/modules/selected.js
> swap in card when hitting max location

- src/components/molecules/ToggleButtons.js
- src/components/seda/SedaHeader.js
- src/css/molecules/_index.css
- src/css/molecules/header-tabs.css
- src/css/molecules/markers.css
- src/css/molecules/toggle-buttons.css
- src/css/variables.css
add prototype functionality for view / toggle component
> prototype: view / toggle component

- src/components/molecules/GradientLegend.js
- src/components/seda/SedaMapChartView.js
- src/constants/dataOptions.js
- src/constants/lang.js
- src/modules/config.js
- src/style/scatterplot-style.js
allows specifying different ranges for what the legend displays and where the colors are placed, closes #161
> Independent Color / Legend Scales

- src/components/seda/SedaExplorerHelp.js
- src/components/seda/SedaMapTooltip.js
- src/components/seda/controls.js
- src/constants/dataOptions.js
- src/constants/lang.js
- src/css/molecules/tooltip.css
- src/css/organisms/section.css
- src/css/organisms/tab-panel.css
- src/css/organisms/visual-help.css
- src/css/variables.css
- src/style/scatterplot-style.js
- adds SES summary to tooltip
- set ranges for the key metrics on for different regions
- remove gaps for user prototype
> add SES to tooltip, set ranges for different regions, cut out gaps

- src/components/molecules/GradientLegend.js
- src/components/organisms/CircleOverlay.js
- src/components/seda/SedaExplorerMap.js
- src/constants/lang.js
- src/css/organisms/dynamic-scatterplot.css
- src/css/organisms/gradient-legend.css
- src/modules/config.js
- show values on gradient label
- update labels to reflect high / low
> update map legend labels to show values

- src/components/atoms/Tooltip.js
- src/components/seda/SedaExplorerChart.js
- src/components/seda/SedaExplorerHelp.js
- src/components/seda/SedaExplorerMap.js
- src/components/seda/SedaHelpAccordion.js
- src/components/seda/SedaMenu.js
- src/components/seda/controls.js
- src/css/molecules/tooltip.css
- src/style/scatterplot-style.js
- src/views/explorer/index.js
- adjust connected `mapStateToProps` functions so they do not generate new objects
> Performance updates

- src/actions/index.js
- src/components/molecules/DivergingBar.js
- src/components/molecules/LegendBar.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/organisms/LocationPanel/LocationStats.js
- src/components/organisms/Map/MapLegend.js
- src/components/organisms/Scatterplot/ScatterplotOverlay.js
- src/components/organisms/Scatterplot/utils.js
- src/components/seda/SedaChart.js
- src/components/seda/SedaLocationMarkers.js
- src/components/seda/SedaSelectControls.js
- src/constants/dataOptions.js
- src/constants/en.js
- src/css/molecules/diverging-bar.css
- src/css/molecules/tooltip.css
- src/modules/config.js
- src/modules/lang.js
- src/utils/index.js
- switch secondary metric to free / reduced lunch
- add functionality to show non-diverging stats
- flip X axis for schools
> Add school metrics

- src/components/molecules/DivergingBar.js
- src/components/organisms/LocationPanel/LocationStats.js
- src/components/seda/SedaChart.js
- src/components/seda/SedaExplorer.js
- src/components/seda/SedaLocationMarkers.js
- src/components/seda/SedaScatterplotPreview.js
- src/components/seda/SedaTooltip.js
- src/constants/dataOptions.js
- src/css/molecules/diverging-bar.css
- src/modules/config.js
- src/utils/index.js
- src/views/sandbox/index.js
fix issue with colors and positions being wrong on diverging stat bar when the range is not balanced
> update diverging bar so midpoint can be anywhere

- src/actions/index.js
- src/components/organisms/LocationPanel/LocationMetricSumary.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/organisms/Scatterplot/utils.js
- src/components/seda/SedaLocationPanel.js
- src/components/seda/SedaSelectControls.js
- src/constants/dataOptions.js
- src/constants/en.js
- src/modules/config.js
- add gaps back into demographic selection
- refactor overlay labels
- trigger gap view from location panel buttons
> re-add gap charts, refactor axis labels

- src/actions/index.js
- src/components/organisms/LocationPanel/LocationMetricSumary.js
- src/components/organisms/LocationPanel/LocationStats.js
- src/components/organisms/Map/MapLegend.js
- src/components/organisms/Scatterplot/utils.js
- src/components/seda/SedaLocationPanel.js
- src/modules/config.js
- src/modules/lang.js
- src/utils/index.js
- src/views/sandbox/index.js
- refactor utility functions
- calculate bar position from midPoint for learning rates so they are accurate
> fix diverging bars for learning rates

- src/actions/index.js
- src/components/organisms/Map/MapLegend.js
- src/components/organisms/Scatterplot/utils.js
- src/components/seda/SedaExplorer.js
- src/components/seda/SedaGapChart.js
- src/components/seda/SedaSelectControls.js
- src/constants/dataOptions.js
- src/constants/en.js
- src/css/organisms/scatterplot.css
- src/css/pages/explorer.css
- src/modules/sections.js
adds secondary chart with selectable x-axis for available gaps
> gap explorer secondary chart

- src/components/organisms/LocationPanel/LocationMetricSumary.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/seda/SedaExplorer.js
- src/constants/en.js
- src/css/atoms/buttons.css
- src/css/organisms/panel.css
- src/css/organisms/scatterplot.css
metric details are now inline with their summary in the location panel
> Reorganize location panel sections

- src/actions/index.js
- src/components/molecules/DivergingBar.js
- src/components/organisms/LocationPanel/LocationComparison.js
- src/components/organisms/LocationPanel/LocationItem.js
- src/components/organisms/LocationPanel/LocationList.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/organisms/LocationPanel/LocationStats.js
- src/components/seda/SedaLocationPanel.js
- src/constants/en.js
- src/css/atoms/buttons.css
- src/css/molecules/diverging-bar.css
- src/css/organisms/location-list.css
- src/css/organisms/panel.css
> Similar locations

- src/components/organisms/Scatterplot/Scatterplot.js
- src/components/organisms/Scatterplot/ScatterplotOverlay.js
- src/components/organisms/Scatterplot/utils.js
- src/components/seda/SedaChart.js
- src/components/seda/SedaGapChart.js
- src/components/seda/SedaHelp.js
- src/constants/dataOptions.js
- src/css/molecules/diverging-bar.css
- src/css/organisms/location-markers.css
- src/modules/config.js
- src/modules/features.js
- size dots based on demographic
- add ranges for size for demographics and regions
- fix bug where 0 values don't have a marker
- fix bug where hovering location marker could show places underneath
> Dot size changes

- src/actions/index.js
- src/components/organisms/LocationPanel/LocationMetricSumary.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/organisms/Scatterplot/utils.js
- src/constants/dataOptions.js
- src/constants/en.js
- src/css/pages/explorer.css
- src/modules/config.js
- src/utils/index.js
- fix bug where poor / non-poor segregation doesn't show
- fix style issue with map legend
- add comparison to average for all locations to location panel for all metrics
- fix preview chart overlay for FRL
- use FRL for location panel when viewing schools
> Add functions to determine how far from avg

- src/components/organisms/Scatterplot/echartTheme.js
- src/components/seda/SedaHeader.js
- src/css/global.css
- src/css/molecules/markers.css
- src/css/molecules/toggle-buttons.css
- src/css/organisms/header.css
- src/css/organisms/location-list.css
- src/css/organisms/location-markers.css
- src/css/organisms/location-preview.css
- src/css/organisms/map-legend.css
- src/css/organisms/scatterplot.css
- src/css/organisms/section.css
- src/css/pages/explorer.css
- src/css/templates/intro-view.css
- src/css/variables.css
- src/style/materialTheme.js
- src/views/index.js
- drop outline / shadows on marker circles
- align marker circles in location panel
- adjust hover state on scatterplot to match other circles
- fix spacing in header to accommodate longer text string
- increase breakpoint for tablet landscape
> style adjustments according to mockups

- src/components/atoms/Logo.js
- src/components/organisms/Scatterplot/utils.js
- src/css/organisms/_index.css
- src/css/organisms/embed.css
- src/css/organisms/scatterplot.css
- src/css/pages/explorer.css
- src/views/embed/ChartEmbedView.js
- src/views/index.js
- Add route for chart embed
- Add chart embed component and styles
> Chart Embed

- package.json
- src/components/organisms/Map/MapLegend.js
- src/components/organisms/Map/selectors.js
- src/components/organisms/Scatterplot/utils.js
- src/components/seda/SedaMap.js
- src/constants/en.js
- src/css/organisms/embed.css
- src/utils/index.js
- src/views/embed/MapEmbedView.js
- src/views/index.js
> Map Embed View

- src/components/molecules/HelpButton.js
- src/components/molecules/Panel.js
- src/components/organisms/LocationPanel/LocationList.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/organisms/Map/MapLegend.js
- src/components/organisms/Scatterplot/echartTheme.js
- src/components/organisms/Scatterplot/utils.js
- src/constants/en.js
- src/css/atoms/typography.css
- src/css/global.css
- src/css/molecules/diverging-bar.css
- src/css/molecules/header-tabs.css
- src/css/molecules/search.css
- src/css/organisms/accordion.css
- src/css/organisms/card.css
- src/css/organisms/embed.css
- src/css/organisms/footer.css
- src/css/organisms/header.css
- src/css/organisms/legend-bar.css
- src/css/organisms/location-list.css
- src/css/organisms/location-preview.css
- src/css/organisms/map-legend.css
- src/css/organisms/panel.css
- src/css/organisms/site-menu.css
- src/css/organisms/summary-group.css
- src/css/variables.css
Style adjustments as provided.
> Style rollup

- package-lock.json
- package.json
- src/actions/index.js
- src/components/organisms/Embed/ChartEmbedView.js
- src/components/organisms/Embed/EmbedDialog.js
- src/components/organisms/Embed/MapEmbedView.js
- src/components/organisms/Embed/index.js
- src/components/seda/SedaFooter.js
- src/components/seda/SedaPage.js
- src/constants/en.js
- src/css/organisms/embed.css
- src/modules/ui.js
- src/views/index.js
- add dialog component
- add copy to clipboard text fields with iframe code
- add embed preview links
- first draft of embed lang
> Embed Dialog

- src/components/organisms/Map/selectors.js
- src/modules/features.js
> Fix null values

- src/components/organisms/LocationPanel/LocationComparison.js
- src/components/organisms/LocationPanel/LocationList.js
- src/css/global.css
> Fix errors fetching similar locations

- src/modules/config.js
> invert bar color for gap metrics

- src/components/organisms/Scatterplot/utils.js
- add "+" to positive axis labels
- add labels to x axis when showing a key metric (closes #232)
- fix bug where learning rates midpoint is not labelled
> update chart axis labels

- src/components/organisms/Scatterplot/Scatterplot.js
- src/components/seda/SedaGapChart.js
- src/css/organisms/map-legend.css
> fix tooltip sticking in firefox

- src/actions/index.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/organisms/Map/style.js
- src/components/seda/SedaExplorer.js
- src/components/seda/SedaLocationPanel.js
- src/constants/en.js
- src/css/global.css
- src/modules/flagged.js
- src/modules/index.js
- src/modules/loading.js
- src/utils/tilequery.js
Adds flags to location panel when a school is marked in the provided data files.  closes #236
> Add School Flags

- public/index.html
- src/components/seda/SedaGapChart.js
- src/components/seda/SedaHelp.js
- src/constants/en.js
- src/constants/statesFips.js
- src/css/organisms/accordion.css
- src/css/organisms/visual-help.css
- src/modules/config.js
- src/modules/sections.js
rebuild "what does the map show" and "what does the chart show" based on new conditionals
> Help Panel Updates

- src/components/organisms/Embed/ChartEmbedView.js
- src/components/organisms/Embed/EmbedDialog.js
- src/components/organisms/Embed/MapEmbedView.js
- src/components/seda/SedaExplorer.js
- src/components/seda/SedaFooter.js
- src/constants/en.js
- src/modules/lang.js
> add tooltip labels, fix embed loading

- src/components/organisms/LocationPanel/LocationMetricSumary.js
- src/components/organisms/LocationPanel/LocationPanel.js
- src/components/seda/SedaGapChart.js
- src/components/seda/SedaLocationPanel.js
- src/constants/en.js
- src/css/molecules/tooltip.css
UPDATES 9/16/19 from https://docs.google.com/document/d/1vqHhO08Os_HSP-jTJCt1vCEYs4gdeRf9h2GD2qG6_ZU/edit?pli=1#heading=h.z6cnt7lfjba9
> language update

- src/components/organisms/LocationPanel/LocationStats.js
> fix gap tooltip for learning rates

- src/components/organisms/Embed/EmbedDialog.js
- src/components/seda/SedaTooltip.js
- src/constants/en.js
- src/css/organisms/embed.css
Adds an additional embed code for the secondary chart if it is active.
> Add secondary chart option to embed dialog

- public/index.html
- src/actions/index.js
- src/components/seda/SedaExplorer.js
- src/store.js
- adds timing tracking for asset load, data load, report generation
- adds problem tracking for load times and report generation
- track data from intro section / loaded URLs
- track when user enters gap view
> Additional analytics

- package-lock.json
- package.json
- src/components/organisms/Scatterplot/Scatterplot.js
- src/constants/statesFips.js
> fix protocol undefined error when fetching schools

- src/components/organisms/Map/MapLegend.js
- src/components/seda/SedaMap.js
- src/components/seda/SedaSearch.js
> fix bug when selecting school from search in gap view

- public/index.html
- src/actions/index.js
> add timing for time spent in different views

- public/index.html
- src/css/organisms/embed.css
> disable analytics on embed routes

- public/index.html
> switch to map view if link is split view on small device

- src/components/seda/SedaHelp.js
> update current view help topics

- src/components/organisms/LocationPanel/LocationComparison.js
- src/components/organisms/Map/MapBase.js
- src/components/seda/SedaLocationPanel.js
- src/css/organisms/map-legend.css
- src/css/organisms/scatterplot.css
- src/css/pages/explorer.css
> close location panel on explore gap press for mobile

- public/index.html
- src/css/organisms/panel.css
closes #278 and fixes ipad issue
> fix for url bar overlapping content

- src/components/organisms/Map/MapBase.js
checks that the map object exists before trying to get the canvas
> fix error where canvas is unavailable

- public/index.html
- src/components/seda/SedaExplorer.js
- do not try and load gap chart if schools
- check for valid route on page load, if invalid redirect to default
> check for valid route on load

- src/components/organisms/LocationPanel/LocationPanel.js
> restore focus to active view toggle

- package-lock.json
- package.json
- src/components/organisms/Scatterplot/Scatterplot.js
- src/components/organisms/Scatterplot/ScatterplotPreview.js
- src/components/seda/SedaChart.js
- src/components/seda/SedaScatterplotPreview.js
- src/css/organisms/map-legend.css
- src/css/organisms/scatterplot.css
- src/modules/scatterplot.js
- adds scatterplot error to redux store
- add styles for scatterplot error
- hide preview chart on scatterplot error
- update react-seda-scatterplot to include update with error message
closes #313
> Handle scatterplot errors

- src/modules/router.js
- add check for number of locations in route, remove if necessary
closes #312
> Limit number of locations in route

- src/components/seda/SedaMap.js
> zoom to the US on default load

- src/components/organisms/Map/MapBase.js
- src/components/organisms/Map/selectors.js
> add highlight borders on school circles

- src/components/organisms/Embed/EmbedDialog.js
- src/css/organisms/embed.css
- add max-width on iframe
- style adjustment on map embed to keep mapbox brand visible
closes #323
> embed updates

- CONTRIBUTING.md
- public/index.html
This PR includes a draft for some contribution guidelines.  The guidelines can be previewed at the following link:
https://github.com/Hyperobjekt/seda-map/blob/doc/contributing/CONTRIBUTING.md
Looking for feedback:
- is this helpful to you?
- is there anything you can think of that is missing?
Open to any suggestions or revisions to this document, guidelines, or processes within it.  If all is good I will merge in and also add similar documentation to the `eviction-maps` repo for Eviction Lab.
> WIP: Contribution Guide

- src/modules/explorer/app/components/SedaExplorer.js
- src/modules/explorer/sharing/components/ShareLinkDialog.js
> connect link share dialog to zustand, add dialog to explorer

- src/modules/explorer/app/constants/site.js
- src/modules/explorer/menu/SedaMenu.js
Recreate site menu in explorer
-Add link material ui to SedaMenu
-Import menu items from constants
-Style links appropriately
(sry for horrible commit comments)
> Issue368 - Explorer site menu

- src/modules/explorer/panels/hooks/useActivePanel.js
> close the active location when selecting another panel

- src/modules/explorer/app/hooks/useDataOptions.js
- src/modules/explorer/app/selectors/demographics.js
- src/modules/explorer/controls/SedaSubgroupSelect.js
- src/modules/explorer/panels/components/SedaDemographicPanel.js
> fix so only appropriate subgroups show in panel

- src/modules/data/useStaticData.js
- src/modules/explorer/app/hooks/useAppContext.js
- src/modules/explorer/scatterplot/components/SedaScatterplotBase.js
- sorts data by # of students when loaded
- sorts scatterplot size by the sizing variable, so large dots appear behind small dots in scatterplot (closes #379)
> fix data sorting

- src/modules/explorer/location/components/SedaDemographicList.js
- src/modules/explorer/location/components/SedaDemographicListItem.js
> fix diverging bar for learning rate values

- src/modules/scatterplot/components/ScatterplotOverlay.js
> fix cutoff overlay dots

- src/modules/explorer/tooltip/SedaTooltip.js
sets bounds on tooltip to keep within viewport, closes #380
> fix tooltip positioning

- src/modules/explorer/location/hooks/useLocationData.js
memoizes active location data, so it does not re-trigger zoom to location.  fixes #415
> fix map re-zooming to location

- src/modules/data/useStaticData.js
- src/modules/explorer/app/hooks/useDataOptions.js
> rename gap variable for non-poor - poor gap

- src/modules/map/style.js
> add road labels at zoom 14

- src/modules/map/components/MapBase.js
> update viewport state after geolocation

- package-lock.json
- package.json
- public/index.html
- src/modules/data/useStaticData.js
- src/modules/explorer/app/hooks/useAppContext.js
- src/modules/explorer/filters/hooks/useFilteredData.js
- src/modules/explorer/loader/components/SedaDataLoader.js
- src/modules/explorer/loader/hooks/useDataLoading.js
- src/modules/explorer/location/hooks/useLocationData.js
- src/modules/explorer/map/SedaMap.js
- src/modules/explorer/panels/components/SedaPanelGroup.js
- src/modules/explorer/tooltip/SedaTooltip.js
- src/modules/map/hooks/useMapStore.js
- switch to papaparse
- adust styles on data loader component (fixes #372)
- use ref caching for app context to help performance
> Fix loading

- src/modules/explorer/scatterplot/utils.js
- src/modules/explorer/search/hooks/useActivateSearchHit.js
> add locations selected via search, fix location marker numbers

- src/modules/explorer/stats/SedaStat.js
> update margin of error accuracy, and formats

- src/modules/explorer/panels/components/SedaCollapsePanel.js
- src/modules/explorer/scatterplot/components/SedaScatterplotBase.js
- src/modules/explorer/scatterplot/components/SedaScatterplotPreview.js
- src/shared/components/BookEnds.js
> update contrast on preview chart, refactor styles

- public/index.html
- src/modules/explorer/routing/hooks/useRouting.js
- src/modules/intro/index.js
- src/modules/map/components/MapBase.js
Closes #466, fixes #467, fixes #468, fixes #469, closes #407
Viewable [here](https://awesome-euler-ab6056.netlify.app/).
> Various bug fixes

- src/modules/explorer/filters/hooks/useActiveFilters.js
> BIE fix: do not apply exclusive flags in regions that do not support it

- src/modules/explorer/app/selectors/metrics.js
> Add scatterplot underlay when filtering locations

- public/index.html
> update static loading screen copy

- src/modules/explorer/app/hooks/useAppContext.js
- src/modules/explorer/scatterplot/components/SedaScatterplot.js
- src/modules/explorer/scatterplot/components/SedaScatterplotBase.js
- src/modules/explorer/scatterplot/style.js
- src/modules/scatterplot/style.js
closes #470, adds an underlay layer of all dots when filter is active
> Add scatterplot underlay

- src/modules/explorer/app/selectors/regions.js
- src/modules/explorer/compare/components/CompareDialog.js
- src/modules/explorer/compare/components/CompareExportButton.js
- src/modules/explorer/compare/components/CompareLoadSimilarButton.js
- src/modules/explorer/location/hooks/useLocationIdsData.js
- src/modules/explorer/map/SedaZoomControls.js
- src/modules/map/components/MapBase.js
Closes #498, closes #480, fixes #499, fixes #479.
Viewable [here](https://focused-engelbart-a57f5e.netlify.app/).
Notes:
- Since we were forced to ditch the Mapbox geolocator and reimplement it using `flyToViewport`, activating geolocation **no longer displays a blue dot at the user's location**.
- Loading similar locations is now disabled for states, showing an explanatory tooltip on hover.
> Various fixes

- package-lock.json
- package.json
- src/modules/explorer/app/hooks/useAppContext.js
- src/modules/explorer/compare/components/CompareDialog.js
- src/modules/explorer/compare/components/CompareLoadSimilarButton.js
- src/modules/explorer/scatterplot/components/SedaScatterplot.js
- src/modules/explorer/scatterplot/components/SedaScatterplotBase.js
- src/modules/explorer/scatterplot/constants.js
- src/modules/filters/useFilterStore.js
- src/modules/filters/utils.js
- src/modules/scatterplot/style.js
- update underlay so it is only active with 5000 or fewer dots
- do not run filters if there are none active
- update progressive rendering to improve underlay performance
> underlay updates

- src/modules/explorer/scatterplot/components/SedaScatterplotBase.js
> update min extents for school poverty

- .gitignore
- scripts/deploy_embargoed.sh
- src/modules/data/useStaticData.js
- src/modules/explorer/app/constants/demographics.js
- src/modules/explorer/app/constants/flags.js
- src/modules/explorer/app/selectors/index.js
- src/modules/explorer/map/SedaZoomControls.js
- src/modules/explorer/map/selectors.js
- src/modules/search/components/AutoComplete.js
when `REACT_APP_SHOW_PR=1` is not present:
- drop "zoom to PR" icon
- drop Puerto Rico search results
- drop Puerto Rico from scatterplot
- drop Puerto Rico from map
> adds conditional to remove Puerto Rico based on ENV vars

- src/modules/explorer/app/constants/flags.js
- src/modules/explorer/filters/components/SedaFilterFlags.js
- src/modules/explorer/filters/hooks/useActiveFilters.js
- src/modules/explorer/routing/selectors.js
Closes #502. 
Viewable [here](https://inspiring-lumiere-20b37d.netlify.app/).
I'm assuming this will need a little bit of refactoring – also I'm having some trouble initializing the BIE environment variable, so any support/confirmation there would be helpful.
> move charter, magnet, bie to exclusive radio buttons

- src/modules/explorer/app/hooks/useAppContext.js
> keep sizes consistent between filtering

- src/modules/explorer/scatterplot/components/SedaScatterplotHeader.js
> change/495 - add new wording to plot title when metric is average test scores

- src/modules/search/components/AutoComplete.js
> remove Puerto Rico cities from search

- src/modules/explorer/stats/SedaStat.js
> hide SedaStat above/below indicator for frl

- src/modules/data/useStaticData.js
- src/modules/explorer/app/selectors/data.js
- src/modules/explorer/location/components/SedaLocationSummary.js
updates SES comparisons function values, removes empty items from the location panel summary
closes #532
closes #534
> update function values

- src/modules/explorer/location/components/DownloadReportButton.js
> feature/428 - add state option to downloadreportButton

- src/modules/explorer/search/components/SedaSearch.js
> filter out cities from search indices

- src/modules/explorer/app/components/SedaApp.js
- src/modules/explorer/app/components/header/SedaHeader.js
- src/modules/explorer/app/components/header/SedaHeaderTitle.js
- src/modules/explorer/help/SedaHelpPanel.js
- src/modules/explorer/location/hooks/useAddLocation.js
- src/modules/explorer/sharing/selectors.js
- src/theme.js
- fix embed on smaller resolutions
- adjust help panel styles
> Fix embed and update help styles

- src/modules/explorer/app/hooks/useAppContext.js
- src/modules/explorer/app/selectors/lang.js
- src/modules/scatterplot/style.js
ensures that data is filtered properly on the charts
> fix filtering for flags

- src/modules/explorer/app/selectors/data.js
- src/modules/explorer/app/selectors/metrics.js
- src/modules/explorer/location/components/SedaLocationSummary.js
- src/modules/explorer/scatterplot/style.js
- Add trend line in development to test the "compared to SES" items in the location panel
- fix bug where "compared to SES" values in the location panel were incorrect
> fix detection of predicted values
